[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
counter = "CCJbUWAzTFUy2VMvcv5b9GWgGgyjcREomzBhsLFudh5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/spec/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
